In [190]:
import sys
from pathlib import Path

In [191]:
root_dir = Path.cwd().parent

In [192]:
if str(root_dir) not in sys.path:
    sys.path.append(str(root_dir))

In [193]:
import geopandas as gpd
import folium
import src.config as cfg

In [194]:
gdf = gpd.read_parquet(cfg.PROCESSED_DIR / "h3.parquet")

In [195]:
lat = 50.0614721
lon = 19.9379908

m_base = folium.Map(location=[lat, lon], zoom_start=12, tiles=None)

folium.TileLayer(tiles="CartoDB Positron", name = "CartoDB Positron",).add_to(m_base)

In [196]:
final_score_map = gdf.explore(column="final_score", cmap="RdYlGn", tooltip=[
    "final_score", "median_price", "value_ratio"], m=m_base, name="Final Score", show=False)
gdf.sort_values(by="final_score").head()

,hex_id,final_score,base_score,destructors,median_price,value_ratio,geometry
1266,891e2e6ab97ffff,0.0,18.768281,73.933954,NaN,NaN,"POLYGON ((20.08623 50.07509, 20.08619 50.07338..."
3050,891e2e6a803ffff,0.0,43.344812,45.119841,NaN,NaN,"POLYGON ((20.06899 50.08274, 20.06896 50.08103..."
1360,891e2e6ababffff,0.0,27.332283,34.006219,NaN,NaN,"POLYGON ((20.09352 50.06741, 20.09348 50.0657,..."
2498,891e2e6f4dbffff,0.0,4.587457,11.017216,NaN,NaN,"POLYGON ((20.12125 50.08546, 20.12122 50.08375..."
1038,891e2e6a877ffff,0.0,32.197112,56.896967,NaN,NaN,"POLYGON ((20.07385 50.07762, 20.07382 50.07591..."

In [197]:
value_ratio_map = gdf.explore(column="value_ratio", cmap="RdYlGn", tooltip=[
    "final_score", "median_price", "value_ratio"], m=m_base, name = "Value Ratio", show=True)
gdf.sort_values(by="value_ratio").head()

,hex_id,final_score,base_score,destructors,median_price,value_ratio,geometry
345,891e2e68e23ffff,2.770760,5.410815,2.640055,11564.66,0.239589,"POLYGON ((20.06282 50.02622, 20.06278 50.02451..."
2171,891e2e68303ffff,6.394776,14.276644,7.881868,15771.93,0.405453,"POLYGON ((20.01568 50.02863, 20.01564 50.02691..."
2139,891e2e68317ffff,8.922506,17.806309,8.883804,14625.85,0.610050,"POLYGON ((20.01822 50.0312, 20.01818 50.02949,..."
2140,891e2e61277ffff,9.745899,9.801103,0.055204,14483.12,0.672914,"POLYGON ((20.03981 50.11343, 20.03978 50.11172..."
3012,891e05a658fffff,9.686684,9.696721,0.010037,14326.92,0.676118,"POLYGON ((19.87602 49.99719, 19.87599 49.99548..."

In [198]:
median_price_map = gdf.explore(column="median_price", cmap="RdYlGn", tooltip=[
    "final_score", "median_price", "value_ratio"], m=m_base, name = "Median price", show=False)
gdf.sort_values(by="median_price").head()

,hex_id,final_score,base_score,destructors,median_price,value_ratio,geometry
3028,891e2e68323ffff,13.811682,20.422815,6.611133,8362.185,1.651683,"POLYGON ((20.02804 50.0261, 20.02801 50.02439,..."
2112,891e2e6ac4bffff,31.286486,33.264945,1.978459,9150.000,3.419288,"POLYGON ((20.03938 50.0929, 20.03934 50.09119,..."
2523,891e2e6accbffff,21.843140,23.316800,1.473660,9150.000,2.387228,"POLYGON ((20.03706 50.10059, 20.03702 50.09888..."
2794,891e2e69e17ffff,29.040363,29.364581,0.324218,9424.720,3.081297,"POLYGON ((19.98272 49.9951, 19.98268 49.99338,..."
714,891e2e69e07ffff,29.787042,30.006224,0.219181,9975.995,2.985872,"POLYGON ((19.98515 49.99254, 19.98511 49.99082..."

In [199]:
folium.LayerControl(collapsed=False).add_to(m_base)

In [200]:
m_base.save("krakow_qol_map.html")